---
title: "cake 预测数据分析"
date: "2023-01-10"
output:
  html_document: default
---

```{r setup, include=FALSE, message=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
```

```{r}
dta <- read_csv("./cake_data.csv")
dta <- dta %>% 
  mutate(
    lock_price = lock_price * 10 ** -8,
    round_oracle_time_diff = close_timestamp - oracle_close_timestamp,
    oracle_close_prev_diff = oracle_close_timestamp - oracle_prev_timestamp
    )
```

## 回合结束时间 - 预言机数据更新时间

回合结束时间平均比预言机最后一次更新时间晚`r mean(dta$round_oracle_time_diff)`秒。数据分布不集中，没有明显的规律，不稳定。

```{r}
ggplot(data = dta, aes(x = round_oracle_time_diff)) + 
  geom_histogram(bins = 50) + 
  theme_bw()
```

### 预言机数据更新间隔

预言机更新间隔的平均值为`r mean(dta$oracle_close_prev_diff)`秒。数据分布集中，是稳定值。

```{r}
ggplot(data = dta, aes(x = oracle_close_prev_diff)) + 
  geom_histogram(bins = 15) + 
  theme_bw()
```

### 比较预言机价格与币安

币安价格取的是包含预言机更新时间那一分钟的k线，其中有那一分钟的最高价和最低价。

985局中，有255局预言机价格与币安最高价差距小于0.001,有290局与币安最低价差距小于0.001。

```{r}
dta %>% 
  group_by(epoch) %>% 
  summarise(
    oracleClose_binanceMax = binance_max_price - lock_price,
    oracleClose_binanceMin = binance_min_price - lock_price,
    oracleClose_binanceMax_four_decimal = abs(oracleClose_binanceMax) < 0.001,
     oracleClose_binanceMin_four_decimal = abs(oracleClose_binanceMin) < 0.001
  ) %>% 
  summarise(
    oracleClose_binanceMax_four_decimal_n = sum(oracleClose_binanceMax_four_decimal),
    oracleClose_binanceMin_four_decimal_n = sum(oracleClose_binanceMin_four_decimal),
    )

```
下图是57293到57436这一百场的价格。黑色是预言机价格，红色是币安最高价，蓝色是币安最低价。黑线不一定在红线和蓝线之间。

```{r}
price <- dta %>% 
  group_by(epoch) %>% 
  summarise(
    oracleClose_binanceMax = binance_max_price - lock_price,
    oracleClose_binanceMin = binance_min_price - lock_price,
    oracleClose_binanceMax_four_decimal = abs(oracleClose_binanceMax) < 0.001,
     oracleClose_binanceMin_four_decimal = abs(oracleClose_binanceMin) < 0.001
  )
dta_100  <- dta %>% head(100)
ggplot(data = dta_100) +
  geom_line(aes(x = epoch, y = lock_price)) + 
  geom_line(aes(x = epoch, y = binance_max_price), color = 'red') +
  geom_line(aes(x = epoch, y = binance_min_price), color = 'blue') +
  theme_bw() +
  ylab('price')
summary(dta_100$epoch)
```

